package com.jettmarks.auth;

// Generated Aug 9, 2014 8:35:05 PM by Hibernate Tools 3.4.0.CR1

/**
 * BikeTrainAuth generated by hbm2java
 */
public class BikeTrainAuth implements java.io.Serializable {

    private Integer id;
    private String email;
    private String password;

    public BikeTrainAuth() {
    }

    public BikeTrainAuth(String email, String password) {
	this.email = email;
	this.password = password;
    }

    public Integer getId() {
	return this.id;
    }

    public void setId(Integer id) {
	this.id = id;
    }

    public String getEmail() {
	return this.email;
    }

    public void setEmail(String email) {
	this.email = email;
    }

    public String getPassword() {
	return this.password;
    }

    public void setPassword(String password) {
	this.password = password;
    }

}
