package com.jettmarks.auth;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;

import com.jettmarks.routes.server.bean.BikeTrain;

// Generated Aug 9, 2014 8:35:05 PM by Hibernate Tools 3.4.0.CR1

/**
 * User generated by hbm2java
 */
@Entity
public class User implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 8749479106838871359L;
    private int userID;
    private String firstName;
    private String lastName;
    private String email;
    private String phone;
    private boolean activeFlag = true; // Default to active
    private boolean privateFlag = true; // Default to private
    private Set<BikeTrain> bikeTrains = new HashSet<BikeTrain>(0);
    private Set<FBAuth> fbAuths = new HashSet<FBAuth>(0);

    public User() {
    }

    public User(int id, String firstName, String lastName, boolean active,
	    boolean private_) {
	this.userID = id;
	this.firstName = firstName;
	this.lastName = lastName;
	this.activeFlag = active;
	this.privateFlag = private_;
    }

    public User(int id, String firstName, String lastName, String email,
	    String phone, boolean active, boolean private_) {
	this.userID = id;
	this.firstName = firstName;
	this.lastName = lastName;
	this.email = email;
	this.phone = phone;
	this.activeFlag = active;
	this.privateFlag = private_;
    }

    @Id
    @GeneratedValue
    @Column(name = "userID")
    public int getUserId() {
	return this.userID;
    }

    public void setUserId(int id) {
	this.userID = id;
    }

    public String getFirstName() {
	return this.firstName;
    }

    public void setFirstName(String firstName) {
	this.firstName = firstName;
    }

    public String getLastName() {
	return this.lastName;
    }

    public void setLastName(String lastName) {
	this.lastName = lastName;
    }

    public String getEmail() {
	return this.email;
    }

    public void setEmail(String email) {
	this.email = email;
    }

    public String getPhone() {
	return this.phone;
    }

    public void setPhone(String phone) {
	this.phone = phone;
    }

    /**
     * @return the activeFlag
     */
    public boolean isActiveFlag() {
	return activeFlag;
    }

    /**
     * @param activeFlag
     *            the activeFlag to set
     */
    public void setActiveFlag(boolean activeFlag) {
	this.activeFlag = activeFlag;
    }

    /**
     * @return the privateFlag
     */
    public boolean isPrivateFlag() {
	return privateFlag;
    }

    /**
     * @param privateFlag
     *            the privateFlag to set
     */
    public void setPrivateFlag(boolean privateFlag) {
	this.privateFlag = privateFlag;
    }

    /**
     * @return the bikeTrains
     */
    @ManyToMany
    @JoinTable(name = "UserTrainMap", joinColumns = { @JoinColumn(name = "userID") }, inverseJoinColumns = { @JoinColumn(name = "trainID") })
    public Set<BikeTrain> getBikeTrains() {
	return bikeTrains;
    }

    /**
     * @param bikeTrains
     *            the bikeTrains to set
     */
    public void setBikeTrains(Set<BikeTrain> bikeTrains) {
	this.bikeTrains = bikeTrains;
    }

    /**
     * @return the fbAuths
     */
    @ManyToMany
    @JoinTable(name = "UserAuthMap", joinColumns = { @JoinColumn(name = "userID") }, inverseJoinColumns = { @JoinColumn(name = "authIdFB") })
    public Set<FBAuth> getFbAuths() {
	return fbAuths;
    }

    /**
     * @param fbAuths
     *            the fbAuths to set
     */
    public void setFbAuths(Set<FBAuth> fbAuths) {
	this.fbAuths = fbAuths;
    }

    public boolean equals(Object other) {
	if ((this == other))
	    return true;
	if ((other == null))
	    return false;
	if (!(other instanceof User))
	    return false;
	User castOther = (User) other;

	return (this.getUserId() == castOther.getUserId())
		&& ((this.getFirstName() == castOther.getFirstName()) || (this
			.getFirstName() != null
			&& castOther.getFirstName() != null && this
			.getFirstName().equals(castOther.getFirstName())))
		&& ((this.getLastName() == castOther.getLastName()) || (this
			.getLastName() != null
			&& castOther.getLastName() != null && this
			.getLastName().equals(castOther.getLastName())))
		&& ((this.getEmail() == castOther.getEmail()) || (this
			.getEmail() != null && castOther.getEmail() != null && this
			.getEmail().equals(castOther.getEmail())))
		&& ((this.getPhone() == castOther.getPhone()) || (this
			.getPhone() != null && castOther.getPhone() != null && this
			.getPhone().equals(castOther.getPhone())))
		&& (this.isActiveFlag() == castOther.isActiveFlag())
		&& (this.isPrivateFlag() == castOther.isPrivateFlag());
    }

    public int hashCode() {
	int result = 17;

	result = 37 * result + this.getUserId();
	result = 37 * result
		+ (getFirstName() == null ? 0 : this.getFirstName().hashCode());
	result = 37 * result
		+ (getLastName() == null ? 0 : this.getLastName().hashCode());
	result = 37 * result
		+ (getEmail() == null ? 0 : this.getEmail().hashCode());
	result = 37 * result
		+ (getPhone() == null ? 0 : this.getPhone().hashCode());
	result = 37 * result + (this.isActiveFlag() ? 1 : 0);
	result = 37 * result + (this.isPrivateFlag() ? 1 : 0);
	return result;
    }

}
