/**
 * Copyright 2009 Jett Marks
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 * 
 * Generated Jan 2, 2011 5:14:55 PM by Hibernate Tools 3.2.4.GA
 */
package com.jettmarks.routes.server.bean;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

/*
 * BikeTrainElementGroupId generated by hbm2java
 */
@Entity
public class BikeTrainElementGroup implements java.io.Serializable
{
  private static final long serialVersionUID = 1L;

  @Column
  private String groupDescription;

  @Id
  @Column(name="ELEMENT_ID")
  private int elementId;

  @Id
  @Column(name="GROUP_ID")
  private int groupId;

  @Column
  private String routeName;

  @Column
  private String leaderName;

  @Column
  private String leaderEmail;

  @Column
  private String leaderPhone;

  @Column
  private String departureTime;

  @Column
  private String arrivalTime;

  @Column
  private String notes;

  public BikeTrainElementGroup()
  {
  }

  public BikeTrainElementGroup(int elementId, int groupId)
  {
    this.elementId = elementId;
    this.groupId = groupId;
  }

  public BikeTrainElementGroup(String groupDescription,
                                 int elementId,
                                 int groupId,
                                 String routeName,
                                 String leaderName,
                                 String leaderEmail,
                                 String leaderPhone,
                                 String departureTime,
                                 String arrivalTime,
                                 String notes)
  {
    this.groupDescription = groupDescription;
    this.elementId = elementId;
    this.groupId = groupId;
    this.routeName = routeName;
    this.leaderName = leaderName;
    this.leaderEmail = leaderEmail;
    this.leaderPhone = leaderPhone;
    this.departureTime = departureTime;
    this.arrivalTime = arrivalTime;
    this.notes = notes;
  }

  public String getGroupDescription()
  {
    return this.groupDescription;
  }

  public void setGroupDescription(String groupDescription)
  {
    this.groupDescription = groupDescription;
  }

  public int getElementId()
  {
    return this.elementId;
  }

  public void setElementId(int elementId)
  {
    this.elementId = elementId;
  }

  public int getGroupId()
  {
    return this.groupId;
  }

  public void setGroupId(int groupId)
  {
    this.groupId = groupId;
  }

  public String getRouteName()
  {
    return this.routeName;
  }

  public void setRouteName(String routeName)
  {
    this.routeName = routeName;
  }

  public String getLeaderName()
  {
    return this.leaderName;
  }

  public void setLeaderName(String leaderName)
  {
    this.leaderName = leaderName;
  }

  public String getLeaderEmail()
  {
    return this.leaderEmail;
  }

  public void setLeaderEmail(String leaderEmail)
  {
    this.leaderEmail = leaderEmail;
  }

  public String getLeaderPhone()
  {
    return this.leaderPhone;
  }

  public void setLeaderPhone(String leaderPhone)
  {
    this.leaderPhone = leaderPhone;
  }

  public String getDepartureTime()
  {
    return this.departureTime;
  }

  public void setDepartureTime(String departureTime)
  {
    this.departureTime = departureTime;
  }

  public String getArrivalTime()
  {
    return this.arrivalTime;
  }

  public void setArrivalTime(String arrivalTime)
  {
    this.arrivalTime = arrivalTime;
  }

  public String getNotes()
  {
    return this.notes;
  }

  public void setNotes(String notes)
  {
    this.notes = notes;
  }

  public boolean equals(Object other)
  {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof BikeTrainElementGroup))
      return false;
    BikeTrainElementGroup castOther = (BikeTrainElementGroup) other;

    return ((this.getGroupDescription() == castOther.getGroupDescription()) || (this.getGroupDescription() != null
                                                                                && castOther.getGroupDescription() != null && this.getGroupDescription()
                                                                                                                                  .equals(
                                                                                                                                      castOther.getGroupDescription())))
           && (this.getElementId() == castOther.getElementId())
           && (this.getGroupId() == castOther.getGroupId())
           && ((this.getRouteName() == castOther.getRouteName()) || (this.getRouteName() != null
                                                                     && castOther.getRouteName() != null && this.getRouteName()
                                                                                                                .equals(
                                                                                                                    castOther.getRouteName())))
           && ((this.getLeaderName() == castOther.getLeaderName()) || (this.getLeaderName() != null
                                                                       && castOther.getLeaderName() != null && this.getLeaderName()
                                                                                                                   .equals(
                                                                                                                       castOther.getLeaderName())))
           && ((this.getLeaderEmail() == castOther.getLeaderEmail()) || (this.getLeaderEmail() != null
                                                                         && castOther.getLeaderEmail() != null && this.getLeaderEmail()
                                                                                                                      .equals(
                                                                                                                          castOther.getLeaderEmail())))
           && ((this.getLeaderPhone() == castOther.getLeaderPhone()) || (this.getLeaderPhone() != null
                                                                         && castOther.getLeaderPhone() != null && this.getLeaderPhone()
                                                                                                                      .equals(
                                                                                                                          castOther.getLeaderPhone())))
           && ((this.getDepartureTime() == castOther.getDepartureTime()) || (this.getDepartureTime() != null
                                                                             && castOther.getDepartureTime() != null && this.getDepartureTime()
                                                                                                                            .equals(
                                                                                                                                castOther.getDepartureTime())))
           && ((this.getArrivalTime() == castOther.getArrivalTime()) || (this.getArrivalTime() != null
                                                                         && castOther.getArrivalTime() != null && this.getArrivalTime()
                                                                                                                      .equals(
                                                                                                                          castOther.getArrivalTime())))
           && ((this.getNotes() == castOther.getNotes()) || (this.getNotes() != null
                                                             && castOther.getNotes() != null && this.getNotes()
                                                                                                    .equals(
                                                                                                        castOther.getNotes())));
  }

  public int hashCode()
  {
    int result = 17;

    result = 37
             * result
             + (getGroupDescription() == null ? 0 : this.getGroupDescription()
                                                        .hashCode());
    result = 37 * result + this.getElementId();
    result = 37 * result + this.getGroupId();
    result = 37
             * result
             + (getRouteName() == null ? 0 : this.getRouteName().hashCode());
    result = 37
             * result
             + (getLeaderName() == null ? 0 : this.getLeaderName().hashCode());
    result = 37
             * result
             + (getLeaderEmail() == null ? 0 : this.getLeaderEmail().hashCode());
    result = 37
             * result
             + (getLeaderPhone() == null ? 0 : this.getLeaderPhone().hashCode());
    result = 37
             * result
             + (getDepartureTime() == null ? 0 : this.getDepartureTime()
                                                     .hashCode());
    result = 37
             * result
             + (getArrivalTime() == null ? 0 : this.getArrivalTime().hashCode());
    result = 37
             * result
             + (getNotes() == null ? 0 : this.getNotes().hashCode());
    return result;
  }

}
