package com.jettmarks.routes.server.bean;

/**
 *   Copyright 2009 Jett Marks
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Generated Nov 21, 2011 10:21:04 PM by Hibernate Tools 3.3.0.GA
 */
// default package

/**
 * BikeTrainGroupId generated by hbm2java
 */
public class BikeTrainGroupId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private String description;
	private String routeName;

	public BikeTrainGroupId() {
	}

	public BikeTrainGroupId(String description, String routeName) {
		this.description = description;
		this.routeName = routeName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getRouteName() {
		return this.routeName;
	}

	public void setRouteName(String routeName) {
		this.routeName = routeName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BikeTrainGroupId))
			return false;
		BikeTrainGroupId castOther = (BikeTrainGroupId) other;

		return ((this.getDescription() == castOther.getDescription()) || (this
				.getDescription() != null
				&& castOther.getDescription() != null && this.getDescription()
				.equals(castOther.getDescription())))
				&& ((this.getRouteName() == castOther.getRouteName()) || (this
						.getRouteName() != null
						&& castOther.getRouteName() != null && this
						.getRouteName().equals(castOther.getRouteName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getDescription() == null ? 0 : this.getDescription()
						.hashCode());
		result = 37 * result
				+ (getRouteName() == null ? 0 : this.getRouteName().hashCode());
		return result;
	}

}
