package com.jettmarks.routes.server.bean;

/**
 *   Copyright 2009 Jett Marks
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Generated Nov 21, 2011 10:21:04 PM by Hibernate Tools 3.3.0.GA
 */
// default package

/**
 * CurrentTrains generated by hbm2java
 */
public class CurrentTrains implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private CurrentTrainsId id;

	public CurrentTrains() {
	}

	public CurrentTrains(CurrentTrainsId id) {
		this.id = id;
	}

	public CurrentTrainsId getId() {
		return this.id;
	}

	public void setId(CurrentTrainsId id) {
		this.id = id;
	}

}
